basket={"orange","apple","mango","apple","orange"}
print(type(basket))
print(basket)
a=set()
a.add(1)
a.add(2)
print(a)
a={}
print(type(a))
a={"somthing"}
print(type(a))
numbers=[1,2,3,4,2,3,4]
unique_numbers=set(numbers)
print(unique_numbers)
unique_numbers.add(5)
print(unique_numbers)
fs=frozenset(numbers)
print(fs)
